let words = ["Buzz", "Tech Trolley", "Honeycomb Showers", "Atlanta", "The Lion King", 
"Finding Nemo", "Tech Green", "Tech Tower", "Ramblin' Wreck", "family", "fireman pole", 
"tow", "spider web", "crow's nest", "sand", "lamp", "enter", "marker", "blush", "shelf", 
"black hole", "stopwatch", "popcorn", "tricycle", "peanut", "coworker", "read", "porthole", 
"geyser", "tide", "paper clips", "spot", "taxidermist", "swoop", "scissors", "bathroom scale", 
"nanny", "sushi", "taxes", "CD", "lifejacket", "waterfall", "rhinoceros", "partner", "obey", 
"windshield", "castle", "harmonica", "teeth", "husband", "day", "garbage", "check", "skirt", 
"package", "pharaoh", "hut", "tulip", "cabin", "cash", "wheelie", "lunar rover", "ski lift", 
"watering can", "bleach", "wick", "fiance", "carpet", "right", "sister", "surround", "yardstick", 
"chairman", "broccoli", "atlas", "hairspray", "snow", "pizza sauce", "base", "hook", "puppet", 
"saxophone", "double", "chef", "yolk", "gown", "twig", "stain", "meat", "trapeze", "palace", 
"hermit crab", "gold", "cucumber", "dustpan", "printer ink", "staple", "handle", "Internet", 
"bowtie", "globe", "pond", "science", "ashamed", "government", "cougar", "engaged", "lid", 
"earmuffs", "chestnut", "step", "trip", "fern", "golf", "rodeo", "cobweb", "smile", "plant", 
"seat", "helicopter", "cousin", "round", "end zone", "state", "flashlight", "blowfish", "rind", 
"wooly mammoth", "sheep dog", "gum", "athlete", "florist", "chocolate chip cookie", "banjo", 
"dodgeball", "sash", "goblin", "disc jockey", "peck", "food", "ink", "t-shirt", "clown", "puddle", 
"grandma", "juice", "chameleon", "pawn", "stroller", "surfboard", "macho", "birthday cake", 
"driveway", "balance beam", "amusement park", "golf cart", "somersault", "loaf", "dance", "nap", 
"deer", "water buffalo", "neighborhood", "flamingo", "tail", "elf", "marshmallow", "irrigation", 
"free", "safe", "garage", "tissue", "wrist", "ski goggles", "traffic jam", "speakers", "twist", 
"download", "hiss", "dawn", "bike", "equator", "Ferris wheel", "landscape", "koala", "banana peel", 
"trampoline", "open", "beach", "torch", "cell phone", "cell phone charger", "drugstore", "doghouse", 
"chin", "popsicle", "paint", "needle", "avocado", "fog", "vanilla", "eye patch", "orange", "invent", 
"porch", "ringleader", "post office", "myth", "goalkeeper", "safety goggles", "pendulum", "password", 
"blanket", "reindeer", "hippopotamus", "bug spray", "putty", "sit", "parachuting", "bald eagle", 
"conveyor belt", "squirrel", "sandpaper", "hen", "student", "locket", "sash", "injury", "librarian", 
"pen", "corner", "fork", "penguin", "monster", "baseball", "shampoo", "clam", "tie", "race car", 
"tugboat", "suitcase", "cheat", "three-toed sloth", "van", "bonnet", "janitor", "movie theater", 
"ditch", "eagle", "radish", "cricket", "airport security", "rattle", "chalk", "middle", "yawn", 
"sleep", "library", "plumber", "tackle", "chart", "honey", "crust", "trombone", "stage", "cemetery", 
"scar", "spear", "pilot", "mug", "fax", "outside", "pantry", "germ", "thermometer", "sailboat", "howl", 
"mascot", "lipstick", "buggy", "wing", "harp", "vest", "limousine", "hoop", "platypus", "edge", "dinner", 
"starfish", "suit", "dirt", "rainstorm", "toothpaste", "trophy", "beanstalk", "great-grandfather", 
"bomb", "tag", "dizzy", "sandal", "poison", "swing dancing", "tightrope", "cork", "narwhal", "wreck", 
"cracker", "wood", "tire", "America", "letter opener", "oxcart", "pulley", "eraser", "flood", 
"synchronized swimming", "toddler", "art", "bell pepper", "backbone", "competition", "cheeseburger", 
"circus", "empty", "plantation", "powder", "rock", "bagel", "gallon", "propeller", "squirt gun", 
"dead end", "chicken coop", "front", "strap", "rose", "banana split", "field", "escalator", "crib", 
"sunrise", "crow", "truck stop", "doctor", "yodel", "beehive", "sticky note", "Jedi", "telephone booth", 
"grasslands", "desk", "muffin", "stomach", "stoplight", "cellar", "feast", "steam", "sunburn", "present", 
"stove", "puzzle", "helium", "flute", "sleeve", "dress", "coin", "scream", "third plate", "tin", 
"dolphin", "oar", "connect", "quarter", "unicorn", "important", "throne", "baby", "degree", "nail", 
"hotel", "newspaper", "east", "connection", "jet ski", "grocery store", "ticket", "foam", "wedge", 
"pea", "geologist", "flu", "barbershop", "seashell", "carousel", "hospital", "saltwater", "firefighter", 
"thrift store", "parka", "leather", "pelican", "ounce", "motorcycle", "religion", "shake", "drums", 
"cactus", "hand soap", "cushion", "see", "weight", "level", "extension cord", "elbow", "seed", "farm", 
"spill", "coastline", "trail", "stow", "organ", "yacht", "brand", "hour", "mop", "hip", "dust bunny", 
"chess", "dream", "drink", "scarecrow", "half", "cliff", "blueprint", "vein", "mold", "owner", "rowboat", 
"welder", "earthquake", "teapot", "college", "coconut", "mine", "stingray", "coast", "basket", "RV", 
"lunch tray", "plow", "chimney", "maze", "flavor", "kettle", "mat", "paperclip", "sweater vest", 
"fireside", "pigpen", "groom", "lecture", "fiddle", "company", "shower curtain", "piano", "summer", 
"potato", "printer", "gasoline", "cobra", "hole", "soda", "soccer", "tourist", "crater", "lunchbox", 
"calm", "lip", "hoof", "scuba diving", "salmon", "sponge", "lumberyard", "prime meridian", "back", 
"drain", "guitar", "ivy", "chime", "glove", "spell", "screwdriver", "dock", "apathetic", "elope", 
"picnic", "cook", "rocking chair", "chariot racing", "crown", "back flip", "page", "strawberry", 
"tusk", "babysitter", "apologize", "tongs", "time", "sandbox", "mysterious", "jewelry", "roof", 
"pirate", "mouth", "cover", "mitten", "saw", "top hat", "shade", "cliff diving", "carat", "scarf", 
"stapler", "shrink ray", "carnival", "laundry detergent", "factory", "wax", "deep", "knight", "turkey", 
"leak", "fin", "poodle", "detective", "fanny pack", "time machine", "pet store", "juggle", "curtains", 
"landlord", "cello", "sugar", "cul-de-sac", "story", "clique", "drawback", "earache", "cardboard", 
"easel", "cast", "hummingbird", "propose", "napkin", "letter", "electrical outlet", "movie", "laser", 
"lace", "reveal", "elephant", "jar", "quadrant", "curtain", "dripping", "pencil", "team", "list", "fur", 
"sink", "playground", "map", "yo-yo", "honk", "compare", "hair", "retail", "orbit", "panda", "cowboy", 
"coat", "thief", "musician", "ski", "frost", "school", "manatee", "hill", "rainbow", "baker", "breakfast", 
"ginger", "flock", "swim", "black belt", "darkness", "eclipse", "desert", "recess", "sunglasses", 
"hurdle", "crime", "ironing board", "chemical", "maid", "trash can", "grill", "wobble", "economics", 
"robin", "quartz", "knee", "catalog", "pogo stick", "blue jeans", "vacation", "porcupine", 
"hot-air balloon", "purse", "song", "last", "correct", "spaceship", "submarine", "tablespoon", 
"ask", "shark", "mini blinds", "pipe", "crumb", "lap", "braid", "windmill", "snowball", "meteor", 
"wallet", "gravity", "yard", "mast", "clog", "pickle", "cough", "ping pong", "grandpa", "stage fright", 
"ribbon", "room", "black widow", "plank", "drive-through", "fungus", "wrench", "dragon", "pain", 
"envelope", "fruit", "electricity", "signal", "sneeze", "shoulder", "banister", "cattle", "seal", 
"mouse", "address", "volcano", "railroad", "caviar", "photosynthesis", "crane", "aunt", "coil", "glass", 
"ladder", "fast food", "mailman"];

exports.Collection = function() {
    return words;
}